[package]
name = "itk-ipc"
description = "Cross-platform IPC channels for the Injection Toolkit"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[dependencies]
itk-protocol = { path = "../itk-protocol" }
thiserror = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
cfg-if = { workspace = true }

[target.'cfg(windows)'.dependencies]
windows = { workspace = true }

[target.'cfg(unix)'.dependencies]
libc = { workspace = true }
nix = { workspace = true }
