[package]
name = "nms-video-launcher"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "nms-video-launcher"
path = "src/main.rs"

[dependencies]
windows = { workspace = true }

[lints]
workspace = true
